//! Deterministic small fixtures under `fixtures/fft-log/` (docs/FIXTURES.md: ≤ 1 MiB
//! each, resolved from `CARGO_MANIFEST_DIR`).
//!
//! Default: verify committed fixture bytes match a fresh in-process generation and
//! pin the recovery/corruption behaviour each file exists for. Drift fails loudly.
//!
//! Opt-in rewrite: set `FFT_REGEN_FIXTURES=1` to overwrite the committed files with
//! freshly generated bytes (intentional format changes only).

mod common;

use std::path::{Path, PathBuf};

use common::{es_meta, mono_events};
use fft_core::CanonicalEvent;
use fft_log::{
    FRAME_HEADER_LEN, INDEX_ENTRY_LEN, IndexSource, LogError, LogReader, LogWriter, SECTION_BOOK,
    SECTION_SESSION, SectionRef, TRAILER_LEN,
};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/fft-log")
}

fn regen_requested() -> bool {
    match std::env::var("FFT_REGEN_FIXTURES") {
        Ok(v) => v == "1" || v.eq_ignore_ascii_case("true"),
        Err(_) => false,
    }
}

fn batches() -> [Vec<CanonicalEvent>; 3] {
    [
        mono_events(60, 1_000_000, 1),
        mono_events(60, 2_000_000, 61),
        mono_events(60, 3_000_000, 121),
    ]
}

/// Base log: three EVENTS frames with a checkpoint between frames 1 and 2, closed.
fn generate_clean_small(path: &Path) -> Vec<u8> {
    let _ = std::fs::remove_file(path);
    let [b0, b1, b2] = batches();
    let mut w = LogWriter::create(path, &es_meta()).unwrap();
    w.append_events(&b0).unwrap();
    w.append_events(&b1).unwrap();
    w.write_checkpoint([
        SectionRef {
            id: SECTION_BOOK,
            version: 1,
            flags: 0,
            bytes: &[0xB0; 256],
        },
        SectionRef {
            id: SECTION_SESSION,
            version: 1,
            flags: 0,
            bytes: &[0x5E; 32],
        },
    ])
    .unwrap();
    w.append_events(&b2).unwrap();
    w.close().unwrap();
    std::fs::read(path).unwrap()
}

/// Same frames but the writer "crashes" (no close): LIVE stays set, no footer.
fn generate_live_base(path: &Path) -> Vec<u8> {
    let _ = std::fs::remove_file(path);
    let [b0, b1, b2] = batches();
    let mut w = LogWriter::create(path, &es_meta()).unwrap();
    for b in [&b0, &b1, &b2] {
        w.append_events(b).unwrap();
    }
    drop(w);
    std::fs::read(path).unwrap()
}

/// Produce each fixture's bytes into a scratch directory (never the committed tree).
fn generate_all_expected(scratch: &Path) -> Vec<(&'static str, Vec<u8>)> {
    std::fs::create_dir_all(scratch).unwrap();

    let clean_path = scratch.join("clean_small.fftlog");
    let clean = generate_clean_small(&clean_path);

    let live_path = scratch.join("live_base.fftlog");
    let live_bytes = generate_live_base(&live_path);
    let (reader, _) = LogReader::open(&live_path).unwrap();
    let final_offset = reader.index()[2].offset;
    drop(reader);
    let cut = final_offset as usize + FRAME_HEADER_LEN + 7; // inside the final payload
    let torn = live_bytes[..cut].to_vec();

    let corrupt_frame_path = scratch.join("corrupt_frame_src.fftlog");
    let mut corrupt_frame = generate_clean_small(&corrupt_frame_path);
    let (reader, _) = LogReader::open(&corrupt_frame_path).unwrap();
    let flip = reader.index()[0].offset as usize + FRAME_HEADER_LEN + 5;
    drop(reader);
    corrupt_frame[flip] ^= 0xff;

    let corrupt_footer_path = scratch.join("corrupt_footer_src.fftlog");
    let mut corrupt_footer = generate_clean_small(&corrupt_footer_path);
    let index_start = corrupt_footer.len() - TRAILER_LEN - 4 * INDEX_ENTRY_LEN;
    corrupt_footer[index_start + 1] ^= 0xff;

    vec![
        ("clean_small.fftlog", clean),
        ("torn_tail.fftlog", torn),
        ("corrupt_frame.fftlog", corrupt_frame),
        ("corrupt_footer.fftlog", corrupt_footer),
    ]
}

fn verify_clean_small(path: &Path) {
    let (reader, report) = LogReader::open(path).unwrap();
    assert_eq!(report.index_source, IndexSource::Footer);
    assert_eq!(reader.frame_count(), 4);
    assert_eq!(reader.read_checkpoint(2).unwrap().len(), 2);
    let events: Vec<_> = reader
        .events(0..reader.frame_count())
        .collect::<Result<_, _>>()
        .unwrap();
    assert_eq!(events, batches().into_iter().flatten().collect::<Vec<_>>());
}

fn verify_torn_tail(path: &Path) {
    let (reader, report) = LogReader::open(path).unwrap();
    let recovery = report.recovery.expect("torn fixture must trigger recovery");
    assert!(recovery.dropped_bytes > 0);
    assert_eq!(reader.frame_count(), 2);
}

fn verify_corrupt_frame(path: &Path) {
    let (reader, _) = LogReader::open(path).unwrap();
    let err = reader.events(0..1).next().unwrap().unwrap_err();
    assert!(matches!(err, LogError::PayloadChecksum { .. }));
}

fn verify_corrupt_footer(path: &Path) {
    let (reader, report) = LogReader::open(path).unwrap();
    assert_eq!(report.index_source, IndexSource::RebuiltCorruptIndex);
    assert!(!report.warnings.is_empty());
    assert_eq!(reader.frame_count(), 4);
}

#[test]
fn fixtures_match_committed_bytes_and_behaviour() {
    let dir = fixtures_dir();
    std::fs::create_dir_all(&dir).unwrap();

    let scratch = std::env::temp_dir().join(format!(
        "fft-log-fixture-gen-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    let expected = generate_all_expected(&scratch);
    let _ = std::fs::remove_dir_all(&scratch);

    let regen = regen_requested();
    for (name, bytes) in &expected {
        let path = dir.join(name);
        if regen {
            std::fs::write(&path, bytes).unwrap();
        } else {
            let committed = std::fs::read(&path).unwrap_or_else(|e| {
                panic!(
                    "committed fixture {name} missing ({e}); generate once with \
                     FFT_REGEN_FIXTURES=1"
                )
            });
            assert_eq!(
                committed, *bytes,
                "fixture {name} drifted from deterministic generation; if the change is \
                 intentional, regenerate with FFT_REGEN_FIXTURES=1"
            );
        }

        match *name {
            "clean_small.fftlog" => verify_clean_small(&path),
            "torn_tail.fftlog" => verify_torn_tail(&path),
            "corrupt_frame.fftlog" => verify_corrupt_frame(&path),
            "corrupt_footer.fftlog" => verify_corrupt_footer(&path),
            _ => unreachable!(),
        }

        let len = std::fs::metadata(&path).unwrap().len();
        assert!(
            len <= 1024 * 1024,
            "{name} is {len} bytes, over the 1 MiB policy cap"
        );
    }
}
